# Use the official Node.js image
FROM node:22.9.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Remove any existing node_modules and package-lock.json to ensure a clean install
RUN rm -rf node_modules package-lock.json && npm install

# Copy the rest of the project files
COPY . .

# Expose the port for Vite development server
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev", "--host"]